name: Build Project

on:
  push:
    branches-ignore:
      - 'dependabot/*'
  workflow_dispatch:

jobs:
  Build:
    uses: evanchooly/workflows/.github/workflows/build.yml@master

  Snapshots:
    if: github.ref_type == 'branch'
    needs:
      - Build
    uses: evanchooly/workflows/.github/workflows/release.yml@master
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GH_TOKEN: ${{ secrets.GH_OAUTH }}

  Critter:
    name: Build Critter snapshot
    needs:
      - Snapshots
    runs-on: ubuntu-latest
    steps:
      - name: Invoke critter build
        uses: benc-uk/workflow-dispatch@v121
        with:
          workflow: "Build Project"
          repo: MorphiaOrg/critter
          token: ${{ secrets.PUSH_TOKEN }}
          ref: refs/heads/master
